controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController
diff_drive_controller:
  ros__parameters:
    left_wheel_names: [front_left_wheel_joint, rear_left_wheel_joint]
    right_wheel_names: [front_right_wheel_joint, rear_right_wheel_joint]
    wheel_separation: 0.246
    wheel_radius: 0.060
    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link
    enable_odom_tf: false
    tf_frame_prefix_enable: false
    position_feedback: true
    open_loop: false
    cmd_vel_timeout: 0.5
    velocity_rolling_window_size: 10
    pose_covariance_diagonal: [0.02, 0.02, 1000000.0, 1000000.0, 1000000.0, 0.05]
    twist_covariance_diagonal: [0.02, 0.02, 1000000.0, 1000000.0, 1000000.0, 0.05]
    linear.x.has_velocity_limits: true
    linear.x.max_velocity: 0.20
    linear.x.min_velocity: -0.20
    linear.x.has_acceleration_limits: true
    linear.x.max_acceleration: 0.4
    linear.x.min_acceleration: -0.4
    angular.z.has_velocity_limits: true
    angular.z.max_velocity: 0.8
    angular.z.min_velocity: -0.8
    angular.z.has_acceleration_limits: true
    angular.z.max_acceleration: 1.0
    angular.z.min_acceleration: -1.0
